### ISSUE TITLE
New bugfix release

### ISSUE THREAD

**Issue by anton-trunov** [dakk/secp256k1-ml#20]
It would be great to have a release with the fix from #19 in place. I'd be happy to help with contributing to the opam repository, but that usually requires to have a dedicated git tag.

**Comment by dakk** [comment]
Done: https://github.com/ocaml/opam-repository/pull/21426
Sorry for that, next time I'll publish a new release after every bugfix

**Comment by dakk** [comment]
@anton-trunov btw, the CI checks are failing: can you address me to a solution?

**Comment by anton-trunov** [comment]
I'm not 100% sure, but it looks like the minimal version of Dune is not compatible. Here is an issue that looks similar: https://github.com/janestreet/core_kernel/issues/87. This has been fixed in Dune v1.3.0 release. Could you please try that Dune version?

**Comment by anton-trunov** [comment]
There is one more reason for build failures: non-Debian-based Linux distros lack the `secp256k1.h` header for some reason. I think this is because [`conf-secp256k1`](https://github.com/ocaml/opam-repository/blob/c0e9300f14d3570da85aad7e6e0ae47484a597a9/packages/conf-secp256k1/conf-secp256k1.1.0.0/opam) does not have the `os-distribution` / `of-family` flags for Alpine, Fedora and Oracle Linux.
